---
version: "3"
services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "36330"
    restart: unless-stopped